[package]
name = "difference_capture"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
crossbeam = "0.8.4"
opencv = "0.88.8"
rayon = "1.8.1"
termion = "3.0.0"
